--;; Data for Name: agreement_state; Type: TABLE DATA; Schema: data_inventory; Owner: data_inventory_writer
INSERT INTO data_inventory.agreement_state (id, name) VALUES
(1, 'Unknown'),
(2, 'Current'),
(3, 'Outdated'),
(4, 'Inexistent'),
(5, 'In Negotiation')
ON CONFLICT DO NOTHING;

--;; Data for Name: agreement_type; Type: TABLE DATA; Schema: data_inventory; Owner: data_inventory_writer
INSERT INTO data_inventory.agreement_type (id, name) VALUES
(1, 'Data Processing Agreement'),
(2, 'Data Use Agreement (Controller-to-Controller Agreement)'),
(3, 'Joint-Controller Agreement'),
(4, 'unknown')
ON CONFLICT DO NOTHING;

--;; Data for Name: country; Type: TABLE DATA; Schema: data_inventory; Owner: data_inventory_writer
INSERT INTO data_inventory.country (id, name, has_gdpr, has_adequacy_decision) VALUES
(1, 'Afghanistan', false, false),
(2, 'Albania', false, false),
(3, 'Algeria', false, false),
(4, 'American Samoa', false, false),
(5, 'Andorra', false, true),
(6, 'Angola', false, false),
(7, 'Anguilla', false, false),
(8, 'Antigua & Barbuda', false, false),
(9, 'Argentina', false, true),
(10, 'Armenia', false, false),
(11, 'Aruba', false, false),
(12, 'Australia', false, false),
(13, 'Austria', true, false),
(14, 'Azerbaijan', false, false),
(15, 'Bahamas, The', false, false),
(16, 'Bahrain', false, false),
(17, 'Bangladesh', false, false),
(18, 'Barbados', false, false),
(19, 'Belarus', false, false),
(20, 'Belgium', true, false),
(21, 'Belize', false, false),
(22, 'Benin', false, false),
(23, 'Bermuda', false, false),
(24, 'Bhutan', false, false),
(25, 'Bolivia', false, false),
(26, 'Bosnia & Herzegovina', false, false),
(27, 'Botswana', false, false),
(28, 'Brazil', false, false),
(29, 'British Virgin Is.', false, false),
(30, 'Brunei', false, false),
(31, 'Bulgaria', true, false),
(32, 'Burkina Faso', false, false),
(33, 'Myanmar', false, false),
(34, 'Burundi', false, false),
(35, 'Cambodia', false, false),
(36, 'Cameroon', false, false),
(37, 'Canada', false, true),
(38, 'Cape Verde', false, false),
(39, 'Cayman Islands', false, false),
(40, 'Central African Rep.', false, false),
(41, 'Chad', false, false),
(42, 'Chile', false, false),
(43, 'China', false, false),
(44, 'Colombia', false, false),
(45, 'Comoros', false, false),
(46, 'Congo, Democratic Republic', false, false),
(47, 'Congo, Republic of the', false, false),
(48, 'Cook Islands', false, false),
(49, 'Costa Rica', false, false),
(50, 'Cote d''Ivoire', false, false),
(51, 'Croatia', true, false),
(52, 'Cuba', false, false),
(53, 'Cyprus', true, false),
(54, 'Czech Republic', true, false),
(55, 'Denmark', true, false),
(56, 'Djibouti', false, false),
(57, 'Dominica', false, false),
(58, 'Dominican Republic', false, false),
(59, 'East Timor', false, false),
(60, 'Ecuador', false, false),
(61, 'Egypt', false, false),
(62, 'El Salvador', false, false),
(63, 'Equatorial Guinea', false, false),
(64, 'Eritrea', false, false),
(65, 'Estonia', true, false),
(66, 'Ethiopia', false, false),
(67, 'Faroe Islands', false, true),
(68, 'Fiji', false, false),
(69, 'Finland', true, false),
(70, 'France', true, false),
(71, 'French Guiana', false, false),
(72, 'French Polynesia', false, false),
(73, 'Gabon', false, false),
(74, 'Gambia, The', false, false),
(75, 'Gaza Strip', false, false),
(76, 'Georgia', false, false),
(77, 'Germany', true, false),
(78, 'Ghana', false, false),
(79, 'Gibraltar', false, false),
(80, 'Greece', true, false),
(81, 'Greenland', false, false),
(82, 'Grenada', false, false),
(83, 'Guadeloupe', false, false),
(84, 'Guam', false, false),
(85, 'Guatemala', false, false),
(86, 'Guernsey', false, true),
(87, 'Guinea', false, false),
(88, 'Guinea-Bissau', false, false),
(89, 'Guyana', false, false),
(90, 'Haiti', false, false),
(91, 'Honduras', false, false),
(92, 'Hong Kong', false, false),
(93, 'Hungary', true, false),
(95, 'India', false, false),
(96, 'Indonesia', false, false),
(97, 'Iran', false, false),
(98, 'Iraq', false, false),
(99, 'Ireland', true, false),
(100, 'Isle of Man', false, true),
(101, 'Israel', false, true),
(102, 'Italy', true, false),
(103, 'Jamaica', false, false),
(104, 'Japan', false, false),
(105, 'Jersey', false, true),
(106, 'Jordan', false, false),
(107, 'Kazakhstan', false, false),
(108, 'Kenya', false, false),
(109, 'Kiribati', false, false),
(110, 'Korea, North', false, false),
(111, 'Korea, South', false, false),
(112, 'Kuwait', false, false),
(113, 'Kyrgyzstan', false, false),
(114, 'Laos', false, false),
(115, 'Latvia', true, false),
(116, 'Lebanon', false, false),
(117, 'Lesotho', false, false),
(118, 'Liberia', false, false),
(119, 'Libya', false, false),
(120, 'Liechtenstein', false, false),
(121, 'Lithuania', true, false),
(122, 'Luxembourg', true, false),
(123, 'Macau', false, false),
(124, 'Macedonia', false, false),
(125, 'Madagascar', false, false),
(126, 'Malawi', false, false),
(127, 'Malaysia', false, false),
(128, 'Maldives', false, false),
(129, 'Mali', false, false),
(130, 'Malta', true, false),
(131, 'Marshall Islands', false, false),
(132, 'Martinique', false, false),
(133, 'Mauritania', false, false),
(134, 'Mauritius', false, false),
(135, 'Mayotte', false, false),
(136, 'Mexico', false, false),
(137, 'Micronesia, Fed. St.', false, false),
(138, 'Moldova', false, false),
(139, 'Monaco', false, false),
(140, 'Mongolia', false, false),
(141, 'Montserrat', false, false),
(142, 'Morocco', false, false),
(143, 'Mozambique', false, false),
(144, 'Namibia', false, false),
(145, 'Nauru', false, false),
(146, 'Nepal', false, false),
(147, 'Netherlands', true, false),
(148, 'Netherlands Antilles', false, false),
(149, 'New Caledonia', false, false),
(150, 'New Zealand', false, true),
(151, 'Nicaragua', false, false),
(152, 'Niger', false, false),
(153, 'Nigeria', false, false),
(154, 'N. Mariana Islands', false, false),
(156, 'Oman', false, false),
(157, 'Pakistan', false, false),
(158, 'Palau', false, false),
(159, 'Panama', false, false),
(160, 'Papua New Guinea', false, false),
(161, 'Paraguay', false, false),
(162, 'Peru', false, false),
(163, 'Philippines', false, false),
(164, 'Poland', true, false),
(165, 'Portugal', true, false),
(166, 'Puerto Rico', false, false),
(167, 'Qatar', false, false),
(168, 'Reunion', false, false),
(169, 'Romania', true, false),
(170, 'Russia', false, false),
(171, 'Rwanda', false, false),
(172, 'Saint Helena', false, false),
(173, 'Saint Kitts & Nevis', false, false),
(155, 'Norway', true, false),
(174, 'Saint Lucia', false, false),
(175, 'St Pierre & Miquelon', false, false),
(176, 'Saint Vincent and the Grenadines', false, false),
(177, 'Samoa', false, false),
(178, 'San Marino', false, false),
(179, 'Sao Tome & Principe', false, false),
(180, 'Saudi Arabia', false, false),
(181, 'Senegal', false, false),
(182, 'Serbia', false, false),
(183, 'Seychelles', false, false),
(184, 'Sierra Leone', false, false),
(185, 'Singapore', false, false),
(186, 'Slovakia', true, false),
(187, 'Slovenia', true, false),
(188, 'Solomon Islands', false, false),
(189, 'Somalia', false, false),
(190, 'South Africa', false, false),
(191, 'Spain', true, false),
(192, 'Sri Lanka', false, false),
(193, 'Sudan', false, false),
(194, 'Suriname', false, false),
(195, 'Swaziland', false, false),
(196, 'Sweden', true, false),
(197, 'Switzerland', false, true),
(198, 'Syria', false, false),
(199, 'Taiwan', false, false),
(200, 'Tajikistan', false, false),
(201, 'Tanzania', false, false),
(202, 'Thailand', false, false),
(203, 'Togo', false, false),
(204, 'Tonga', false, false),
(205, 'Trinidad & Tobago', false, false),
(206, 'Tunisia', false, false),
(207, 'Turkey', false, false),
(208, 'Turkmenistan', false, false),
(209, 'Turks & Caicos Is', false, false),
(210, 'Tuvalu', false, false),
(211, 'Uganda', false, false),
(212, 'Ukraine', false, false),
(213, 'United Arab Emirates', false, false),
(214, 'United Kingdom', true, false),
(215, 'United States', false, false),
(216, 'Uruguay', false, true),
(217, 'Uzbekistan', false, false),
(218, 'Vanuatu', false, false),
(219, 'Venezuela', false, false),
(220, 'Vietnam', false, false),
(221, 'Virgin Islands', false, false),
(222, 'Wallis and Futuna', false, false),
(223, 'West Bank', false, false),
(224, 'Western Sahara', false, false),
(225, 'Yemen', false, false),
(226, 'Zambia', false, false),
(227, 'Zimbabwe', false, false),
(228, 'Montenegro', false, false),
(229, 'Kosovo', false, false),
(230, 'South Sudan', false, false),
(94, 'Iceland', true, false),
(231, '#Cluster', false, false)
ON CONFLICT DO NOTHING;

--;; Data for Name: data_source; Type: TABLE DATA; Schema: data_inventory; Owner: data_inventory_writer
INSERT INTO data_inventory.data_source (id, name, description, has_eprivacy_content, has_eprivacy_meta, rank) VALUES
(17, 'Third Party (EU/EEA) – Telecommunications Content Data', 'Telecommunicatons Content Data obtained from a third party, such as a BU.', true, false, 10),
(1, 'Data Subject – Active Data Capture (Data Entry by the User)', 'Data that the data subject has entered him- or herself.', false, false, 1),
(5, 'Internal System – Non-Telecommunications Data', 'Data that stems from a service/system that the Product Owner operates, and which is not Telecommunications Data.', false, false, 3),
(11, 'Third Party – Non-Telecommunications Data', 'Data obtained from a third party, such as a BU, which is not Telecommunications Data and not openly available to everyone.', false, false, 6),
(10, 'Data Subject – Passive Data Capture (from the User''s System/Device)', 'Data that stems from the system/device used by the data subject, but is not actively entered by the data subject him- or herself.', false, false, 2),
(13, 'Internal System – Telecommunications Content Data', 'Content Data that is captured from Telecommunication Processes within a service/system that the Product Owner operates.', true, false, 4),
(18, 'Third Party (non-EU/EEA) – Telecommunications Content Data', 'Telecommunicatons Content Data obtained from a third party, such as a BU.', true, false, 11),
(12, 'Openly Available Source', 'Data obtained from a source that is openly available to everyone.', false, false, 12),
(9, 'Public Authority', 'Data obtained from a legal person of public law, e.g. authorities.', false, false, 13),
(15, 'Third Party (EU/EEA) – Telecommunications Meta Data', 'Telecommunications Meta Data (i.e. MSISDN if originally captured from a telco stream, i.e. by DPI/DNA) obtained from a third party, such as a BU.', false, true, 8),
(16, 'Third Party (non-EU/EEA) – Telecommunications Meta Data', 'Telecommunications Meta Data (i.e. MSISDN if originally captured from a telco stream, i.e. by DPI/DNA) obtained from a third party, such as a BU.', false, true, 9),
(4, 'Internal System – Telecommunications Meta Data', 'Telecommunications Meta Data (i.e. MSISDN if originally captured from a telco stream, i.e. by DPI/DNA) obtained from a telco network operated by ourselves.', false, true, 5)
ON CONFLICT DO NOTHING;

--;; Data for Name: data_subject_category; Type: TABLE DATA; Schema: data_inventory; Owner: data_inventory_writer
INSERT INTO data_inventory.data_subject_category (id, name, description) VALUES
(4, 'Unknown', NULL),
(2, 'Telenor Digital Employee', NULL),
(1, 'Telenor Digital Product (End-)User', NULL),
(3, 'Telenor Digital Third-Party (Person not linked to Telenor Digital)', NULL),
(1001, 'Telenor Health Employee', NULL),
(1002, 'Telenor Health Product (End-)User', NULL),
(1003, 'Telenor Health Third-Party (Person not linked to Telenor Health)', NULL)
ON CONFLICT DO NOTHING;

--;; Data for Name: data_subject_location; Type: TABLE DATA; Schema: data_inventory; Owner: data_inventory_writer
INSERT INTO data_inventory.data_subject_location (id, name) VALUES
(1, 'Unknown'),
(2, 'EU'),
(3, 'EEA(Non-EU)'),
(4, 'Non-EEA/Non-EU')
ON CONFLICT DO NOTHING;

--;; Data for Name: dpia_state; Type: TABLE DATA; Schema: data_inventory; Owner: data_inventory_writer
INSERT INTO data_inventory.dpia_state (id, name) VALUES
(1, 'Unknown'),
(2, 'Current'),
(3, 'Outdated'),
(4, 'Inexistent')
ON CONFLICT DO NOTHING;

--;; Data for Name: legal_basis; Type: TABLE DATA; Schema: data_inventory; Owner: data_inventory_writer
INSERT INTO data_inventory.legal_basis (id, name, article, is_consent, source) VALUES
(1, 'General Consent', 'Art. 6 I a) GDPR', true, 'GDPR'),
(2, 'Performance of a Contract', 'Art. 6 I b) GDPR', false, 'GDPR'),
(3, 'Compliance with a Legal Obligation', 'Art. 6 I c) GDPR', false, 'GDPR'),
(4, 'Public Interest', 'Art. 6 I d) GDPR', false, 'GDPR'),
(5, 'Legitimate Interest', 'Art. 6 I e) GDPR', false, 'GDPR'),
(6, 'Consent for Special Categories', 'Art. 9 II a) GDPR', true, 'GDPR'),
(7, 'Employment and Social Security Cases', 'Art. 9 II b) GDPR', false, 'GDPR'),
(8, 'Vital Interests', 'Art. 9 II c) GDPR', false, 'GDPR'),
(9, 'Data manifestly made public by Data Subject', 'Art. 9 II e) GDPR', false, 'GDPR'),
(10, 'Legal Claims', 'Art. 9 II f) GDPR', false, 'GDPR'),
(11, 'Substantial Public Interest', 'Art. 9 II g) GDPR', false, 'GDPR'),
(12, 'Preventive and Occupational Medicine, incl. Working Capacity of Employees', 'Art. 9 II h) GDPR', false, 'GDPR'),
(13, 'Public Health', 'Art. 9 II i) GDPR', false, 'GDPR'),
(14, 'Archiving in the Public Interest and Scientific Research', 'Art. 9 II j) GDPR', false, 'GDPR'),
(15, 'Performance of a Contract for Profiling', 'Art. 22 II a) GDPR', false, 'GDPR'),
(16, 'Other Explicit Legal Basis for Profiling', 'Art. 22 II b) GDPR', false, 'GDPR'),
(17, 'Consent for Profiling', 'Art. 22 II c) GDPR', true, 'GDPR'),
(18, 'Processing as a Processor', 'Art. 28 GDPR', false, 'GDPR'),
(19, 'Adequacy Decision (Transfer)', 'Art. 45 GDPR', false, 'GDPR'),
(20, 'Binding Corporate Rules (Transfer)', 'Art. 46 II c), Art. 47 GDPR', false, 'GDPR'),
(21, 'Standard Data Protection Clauses (SCC) (Transfer)', 'Art. 46 II d) GDPR', false, 'GDPR'),
(22, 'Approved Code of Conduct (Transfer)', 'Art 46 II e), Art. 40 GDPR', false, 'GDPR'),
(23, 'Certification (Transfer)', 'Art. 46 II f), Art. 42 GDPR', false, 'GDPR'),
(24, 'Consent for Transfer', 'Art. 49 I a) GDPR', true, 'GDPR'),
(25, 'Performance of a Contract with the Data Subject (Transfer)', 'Art. 49 I b) GDPR', false, 'GDPR'),
(26, 'Performance of a Contract concluded in the Interest of the Data Subject (Transfer)', 'Art. 49 I c) GDPR', false, 'GDPR'),
(27, 'Public Interest (Transfer)', 'Art. 49 I d) GDPR', false, 'GDPR'),
(28, 'Legal Claim (Transfer)', 'Art. 49 I e) GDPR', false, 'GDPR'),
(29, 'Vital Interests (Transfer)', 'Art. 49 I f) GDPR', false, 'GDPR'),
(30, 'Neccessary to achieve transmission', 'Art. 6 I a) ePrivacy Regulation', false, 'ePrivacy Regulation'),
(31, 'Maintain Network Security and Functionality', 'Art. 6 I b) ePrivacy Regulation', false, 'ePrivacy Regulation'),
(32, 'Meet Mandatory Quality of Service Requirements (Metadata)', 'Art. 6 II a) ePrivacy Regulation', false, 'ePrivacy Regulation'),
(33, 'Billing, Interconnection Payment and Fraud Prevention (Metadata)', 'Art. 6 II b) ePrivacy Regulation', false, 'ePrivacy Regulation'),
(34, 'Consent for Telecommunications Metadata', 'Art. 6 II c) ePrivacy Regulation', true, 'ePrivacy Regulation'),
(35, 'Consent for Telecommuncations Content Data for Service Provision', 'Art. 6 III a) ePrivacy Regulation', true, 'ePrivacy Regulation'),
(36, 'Consent for Telecommunications ContentData for Purposes other than Service Provision', 'Art. 6 III b) ePrivacy Regulation', true, 'ePrivacy Regulation'),
(39, 'Consent for Direct Marketing', 'Art. 16 I ePrivacy Regulation', true, 'ePrivacy Unsolicited Marketing'),
(40, 'Direct Marketing of Own Similar Products', 'Art. 16 II ePrivacy Regulation', true, 'ePrivacy Unsolicited Marketing'),
(37, 'No Legal Basis', NULL, false, NULL),
(1001, 'Requirement: Other Legal Basis for Transfer, such as CoC, Certificatio, Performance of Contract or Consent.', 'Art. 46 II GDPR, Art. 49 I GDPR', false, 'GDPR'),
(38, 'Transfer within EU/EEA: no 3rd country legal basis required', NULL, false, 'GDPR')
ON CONFLICT DO NOTHING;

--;; Data for Name: owner_role; Type: TABLE DATA; Schema: data_inventory; Owner: data_inventory_writer
INSERT INTO data_inventory.owner_role (id, name) VALUES
(1, 'Processor'),
(2, 'Controller'),
(3, 'ECS provider'),
(4, 'Joint controller'),
(5, 'Unknown'),
(6, 'Sub-Processor'),
(1001, 'Data Subject')
ON CONFLICT DO NOTHING;

--;; Data for Name: owner_type; Type: TABLE DATA; Schema: data_inventory; Owner: data_inventory_writer
INSERT INTO data_inventory.owner_type (id, name) VALUES
(1, 'Telenor Group'),
(2, 'B2B Vendor'),
(3, 'B2B Customer'),
(4, 'Authority'),
(5, 'Devices of natural persons (customers)'),
(6, 'Devices of natural persons (non-customers)'),
(7, 'Unknown owner type')
ON CONFLICT DO NOTHING;

--;; Data for Name: person_role; Type: TABLE DATA; Schema: data_inventory; Owner: data_inventory_writer
INSERT INTO data_inventory.person_role (id, name) VALUES
(1, 'Product owner'),
(2, 'Technical lead'),
(3, 'Security contact'),
(4, 'Privacy contact')
ON CONFLICT DO NOTHING;

--;; Data for Name: product_group; Type: TABLE DATA; Schema: data_inventory; Owner: data_inventory_writer
INSERT INTO data_inventory.product_group (id, name) VALUES
(1, 'Global Platforms'),
(2, 'Digital Sales & Marketing'),
(3, 'Digital Care'),
(4, 'Software Telco'),
(5, 'Telenor Health'),
(6, 'Technology & Services'),
(7, 'Unknown/Undefined')
ON CONFLICT DO NOTHING;

--;; Data for Name: use_case_state; Type: TABLE DATA; Schema: data_inventory; Owner: data_inventory_writer
INSERT INTO data_inventory.use_case_state (id, name) VALUES
(1, 'Unknown'),
(2, 'Current'),
(3, 'Future'),
(4, 'Past')
ON CONFLICT DO NOTHING;
